export const memberDetails = [
  {
    type: "text",
    name: "name",
    label: "Name",
    mandatory: <span className="text-red-500 tracking-wide">&#42;</span>,
    disable: "details",
    placeholder: "Provide Name",
  },
  {
    type: "textarea",
    name: "current_address",
    label: " Current Address",
    mandatory: <span className="text-red-500 tracking-wide">&#42;</span>,
    disable: "details",
    placeholder: "Provide Address...",
  },
  {
    type: "text",
    name: "mobile",
    label: "Mobile",
    mandatory: <span className="text-red-500 tracking-wide">&#42;</span>,
    disable: "details",
    placeholder: "Provide Number",
  },
  {
    type: "text",
    name: "full_name",
    label: " Full Name",
    mandatory: <span className="text-red-500 tracking-wide">&#42;</span>,
    disable: "details",
    placeholder: "Provide Full Name",
  },
  {
    type: "text",
    name: "district",
    label: " District",
    mandatory: <span className="text-red-500 tracking-wide">&#42;</span>,
    disable: "details",
    placeholder: "Provide District",
  },
  {
    type: "text",
    name: "local_gov",
    label: "  VDC/Municiaplity",
    mandatory: <span className="text-red-500 tracking-wide">&#42;</span>,
    disable: "details",
    placeholder: "Provide VDC/Municipality",
  },
  {
    type: "text",
    name: "ward_no",
    label: " Ward No.",
    mandatory: <span className="text-red-500 tracking-wide">&#42;</span>,
    disable: "details",
    placeholder: "Provide Ward No.",
  },
  {
    type: "text",
    name: "street_or_tole",
    label: " Street/Tole",
    mandatory: "",
    disable: "details",
    placeholder: "Provide Street/Tole Name",
  },
  {
    type: "text",
    name: "country",
    label: " Country",
    mandatory: <span className="text-red-500 tracking-wide">&#42;</span>,
    disable: "details",
    placeholder: "Provide Country",
  },
  {
    type: "text",
    name: "citizenship",
    label: " Citizenship/Passport No.",
    mandatory: "",
    disable: "details",
    placeholder: "Provide Citizenship/Password No.",
  },
  {
    type: "textarea",
    name: "medical_problems",
    label: " Any Medical Problems We Should Be Aware Of",
    mandatory: "",
    disable: "details",
    placeholder: "Write if medical problems...",
  },
];

export const emergencyContact = [
  {
    type: "text",
    name: "emergency_contact_name",
    label: "Name",
    disable: "details",
    placeholder: "Provide Name",
  },
  {
    type: "text",
    name: "emergency_contact_relationship",
    label: "Relationship",
    disable: "details",
    placeholder: "Mention Relationship",
  },
  {
    type: "textarea",
    name: "emergency_contact_address",
    label: "Address",
    disable: "details",
    placeholder: "Mention Relationship",
  },
  {
    type: "text",
    name: "emergency_contact_phone",
    label: " Phone Number",
    disable: "details",
    placeholder: "Provide Phone Number",
  },
];
