// form update
export const FORM_UPDATED = "FORM_UPDATED";
// profile
export const PICTURE_CHANGE = "PICTURE_CHANGE";
// sidebar
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
// members
export const SET_MEMBERS = "SET_MEMBERS";
export const SET_VALID_MEMBERS = "SET_VALID_MEMBERS";
export const SET_EXPIRED_MEMBERS = "SET_EXPIRED_MEMBERS";
export const SET_EXPIRY_VALID_MEMBERS = "SET_EXPIRY_VALID_MEMBERS";
export const SELECTED_VALID_MEMBER = "SELECTED_VALID_MEMBER";
export const SET_JOINED_MEMBERS_COUNT = "SET_JOINED_MEMBERS_COUNT";
export const SET_MEMBER_BY_ID = "SET_MEMBER_BY_ID";
export const REMOVE_SELECTED_MEMBER = "REMOVE_SELECTED_MEMBER";
export const REMOVE_SELECTED_VALID_MEMBER = "REMOVE_SELECTED_VALID_MEMBER";

// system users
export const SET_LOGGEDIN_USER = "SET_LOGGEDIN_USER";
export const REMOVE_LOGGEDIN_USER = "REMOVE_LOGGEDIN_USER";
export const SET_GROUP_DATA = "SET_GROUP_DATA";
export const SET_USER_DATA = "SET_USER_DATA";
